#!/bin/bash
set -euo pipefail

# generate-compose.sh — Generates docker-compose.yml from bots/ directory
# Run this whenever bots are added or removed.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
BOTS_DIR="$SCRIPT_DIR/bots"
PORT_REGISTRY="$BOTS_DIR/.port-registry"
BASE_PORT=18789

if [ ! -f "$PORT_REGISTRY" ] || [ ! -s "$PORT_REGISTRY" ]; then
    echo "⚠️  No bots registered. Run deploy-bot.sh first."
    exit 0
fi

# Start building the compose file
cat > "$COMPOSE_FILE" << 'HEADER'
# ============================================================
# AUTO-GENERATED by generate-compose.sh — DO NOT EDIT MANUALLY
# To add/remove bots, use deploy-bot.sh / remove-bot.sh
# Then run: ./generate-compose.sh
# ============================================================

services:
HEADER

VOLUMES=""

while IFS=' ' read -r bot_name port_offset; do
    # Skip empty lines and comments
    [[ -z "$bot_name" || "$bot_name" == \#* ]] && continue

    # Validate bot directory exists
    if [ ! -d "$BOTS_DIR/$bot_name" ]; then
        echo "⚠️  Warning: Bot '$bot_name' in registry but no bots/$bot_name/ directory. Skipping."
        continue
    fi

    if [ ! -f "$BOTS_DIR/$bot_name/config.json" ]; then
        echo "⚠️  Warning: No config.json for bot '$bot_name'. Skipping."
        continue
    fi

    EXTERNAL_PORT=$((BASE_PORT + port_offset - 1))
    SERVICE_NAME="openclaw-bot-${bot_name}"
    # Convert bot_name to uppercase and replace hyphens with underscores for env var
    ENV_VAR_SUFFIX=$(echo "$bot_name" | tr '[:lower:]-' '[:upper:]_')

    cat >> "$COMPOSE_FILE" << EOF
  ${SERVICE_NAME}:
    build:
      context: .
      dockerfile: Dockerfile
    image: openclaw-bot:latest
    container_name: ${SERVICE_NAME}
    environment:
      - TELEGRAM_BOT_TOKEN=\${TOKEN_${ENV_VAR_SUFFIX}}
    ports:
      - "${EXTERNAL_PORT}:18789"
    volumes:
      - ${SERVICE_NAME}:/home/node/.openclaw
      - ./bots/${bot_name}/config.json:/config/config.json:ro
    mem_limit: 2g
    memswap_limit: 11g
    restart: unless-stopped

EOF

    VOLUMES="${VOLUMES}  ${SERVICE_NAME}:\n"

done < "$PORT_REGISTRY"

# Write volumes section
echo "volumes:" >> "$COMPOSE_FILE"
printf "%b" "$VOLUMES" >> "$COMPOSE_FILE"

BOT_COUNT=$(grep -c 'container_name:' "$COMPOSE_FILE" || echo "0")
echo "✅ Generated docker-compose.yml with ${BOT_COUNT} bot(s)"
