#!/bin/bash
set -euo pipefail

# generate-compose.sh — Generates docker-compose.yml AND nginx configs from bots/ directory
# Run this whenever bots are added or removed.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
BOTS_DIR="$SCRIPT_DIR/bots"
PORT_REGISTRY="$BOTS_DIR/.port-registry"
BASE_PORT=18789

# Nginx settings (read domain from nginx/.env)
NGINX_DIR="$SCRIPT_DIR/../nginx"
NGINX_CONF_DIR="$NGINX_DIR/conf.d"
NGINX_ENV="$NGINX_DIR/.env"

if [ -f "$NGINX_ENV" ]; then
    DOMAIN=$(grep '^DOMAIN=' "$NGINX_ENV" | cut -d'=' -f2-)
fi

if [ -z "${DOMAIN:-}" ]; then
    echo "❌ DOMAIN not set. Configure it in nginx/.env"
    echo "   DOMAIN=yourdomain.com"
    exit 1
fi

if [ ! -f "$PORT_REGISTRY" ] || [ ! -s "$PORT_REGISTRY" ]; then
    echo "⚠️  No bots registered. Run deploy-bot.sh first."
    exit 0
fi

# Ensure nginx conf.d directory exists
mkdir -p "$NGINX_CONF_DIR"

# Start building the compose file
cat > "$COMPOSE_FILE" << 'HEADER'
# ============================================================
# AUTO-GENERATED by generate-compose.sh — DO NOT EDIT MANUALLY
# To add/remove bots, use deploy-bot.sh / remove-bot.sh
# Then run: ./generate-compose.sh
# ============================================================

services:
HEADER

VOLUMES=""
ACTIVE_BOTS=()

while IFS=' ' read -r bot_name port_offset; do
    # Skip empty lines and comments
    [[ -z "$bot_name" || "$bot_name" == \#* ]] && continue

    # Validate bot directory exists
    if [ ! -d "$BOTS_DIR/$bot_name" ]; then
        echo "⚠️  Warning: Bot '$bot_name' in registry but no bots/$bot_name/ directory. Skipping."
        continue
    fi

    if [ ! -f "$BOTS_DIR/$bot_name/config.json" ]; then
        echo "⚠️  Warning: No config.json for bot '$bot_name'. Skipping."
        continue
    fi

    EXTERNAL_PORT=$((BASE_PORT + port_offset - 1))
    SERVICE_NAME="openclaw-bot-${bot_name}"
    # Convert bot_name to uppercase and replace hyphens with underscores for env var
    ENV_VAR_SUFFIX=$(echo "$bot_name" | tr '[:lower:]-' '[:upper:]_')

    cat >> "$COMPOSE_FILE" << EOF
  ${SERVICE_NAME}:
    build:
      context: .
      dockerfile: Dockerfile
    image: openclaw-bot:latest
    container_name: ${SERVICE_NAME}
    environment:
      - TELEGRAM_BOT_TOKEN=\${TOKEN_${ENV_VAR_SUFFIX}}
      - NODE_OPTIONS=--max-old-space-size=768
      - BOT_ORIGIN=https://${bot_name}.${DOMAIN}
    ports:
      - "${EXTERNAL_PORT}:18789"
    volumes:
      - ${SERVICE_NAME}:/home/node/.openclaw
      - ./bots/${bot_name}/config.json:/config/config.json:ro
    shm_size: '256m'
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    networks:
      - bot-proxy-net

EOF

    VOLUMES="${VOLUMES}  ${SERVICE_NAME}:\n"

    # Track active bot for nginx cleanup
    ACTIVE_BOTS+=("$bot_name")

    # Generate nginx config for this bot
    cat > "${NGINX_CONF_DIR}/${bot_name}.conf" << NGINX_EOF
# AUTO-GENERATED by generate-compose.sh — DO NOT EDIT MANUALLY
# Bot: ${bot_name} → ${bot_name}.${DOMAIN}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${bot_name}.${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    # Proxy to bot container (via shared Docker network)
    location / {
        proxy_pass http://${SERVICE_NAME}:18789;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;

        # Timeouts for long-running AI requests
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_connect_timeout 10s;

        # Rate limiting
        limit_req zone=general burst=20 nodelay;
    }

    # Health check endpoint (no rate limit)
    location /health {
        proxy_pass http://${SERVICE_NAME}:18789/health;
        proxy_set_header Host \$host;
        access_log off;
    }
}
NGINX_EOF
    echo "  📝 Generated nginx config: ${bot_name}.${DOMAIN}"

done < "$PORT_REGISTRY"

# Write volumes section
echo "volumes:" >> "$COMPOSE_FILE"
printf "%b" "$VOLUMES" >> "$COMPOSE_FILE"

# Add shared network for nginx reverse proxy
cat >> "$COMPOSE_FILE" << 'NETWORK_EOF'

networks:
  bot-proxy-net:
    external: true
NETWORK_EOF

# Clean up stale nginx configs (for removed bots)
# Protect non-bot configs: api.conf is managed separately below
PROTECTED_CONFIGS=("api")
if [ -d "$NGINX_CONF_DIR" ]; then
    for conf_file in "$NGINX_CONF_DIR"/*.conf; do
        [ -f "$conf_file" ] || continue
        conf_basename=$(basename "$conf_file" .conf)

        # Skip protected (non-bot) configs
        skip=false
        for protected in "${PROTECTED_CONFIGS[@]}"; do
            if [ "$conf_basename" = "$protected" ]; then
                skip=true
                break
            fi
        done
        [ "$skip" = true ] && continue

        found=false
        for active_bot in "${ACTIVE_BOTS[@]}"; do
            if [ "$conf_basename" = "$active_bot" ]; then
                found=true
                break
            fi
        done
        if [ "$found" = false ]; then
            rm -f "$conf_file"
            echo "  🗑️  Removed stale nginx config: ${conf_basename}.conf"
        fi
    done
fi

# Generate nginx config for Management API → api.${DOMAIN}
cat > "${NGINX_CONF_DIR}/api.conf" << NGINX_API_EOF
# AUTO-GENERATED by generate-compose.sh — DO NOT EDIT MANUALLY
# Management API → api.${DOMAIN}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name api.${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    # Security headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    # Proxy to API container (via shared Docker network)
    location / {
        proxy_pass http://openclaw-api:18800;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_http_version 1.1;

        # Timeouts for deploy/remove operations (can take up to 2 min)
        proxy_read_timeout 180s;
        proxy_send_timeout 30s;
        proxy_connect_timeout 10s;

        # Rate limiting
        limit_req zone=general burst=20 nodelay;
    }

    # Health check endpoint (no rate limit)
    location /api/v1/health {
        proxy_pass http://openclaw-api:18800/api/v1/health;
        proxy_set_header Host \$host;
        access_log off;
    }
}
NGINX_API_EOF
echo "  📝 Generated nginx config: api.${DOMAIN}"

# Generate nginx.conf with correct domain for SSL cert paths
cat > "$NGINX_DIR/nginx.conf" << MAIN_NGINX_EOF
# AUTO-GENERATED by generate-compose.sh — DO NOT EDIT MANUALLY
# Domain sourced from nginx/.env: ${DOMAIN}

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                      '\$status \$body_bytes_sent "\$http_referer" '
                      '"\$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush      on;
    keepalive_timeout  65;
    gzip  on;

    # WebSocket support (for OpenClaw dashboard live updates)
    map \$http_upgrade \$connection_upgrade {
        default upgrade;
        ''      close;
    }

    # Rate limiting
    limit_req_zone \$binary_remote_addr zone=general:10m rate=10r/s;

    # SSL settings (shared across all server blocks)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # DNS resolver (for OCSP stapling in server blocks)
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # Default server — handle HTTP (ACME challenge + redirect)
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        # ACME challenge for certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect all other HTTP to HTTPS
        location / {
            return 301 https://\$host\$request_uri;
        }
    }

    # Default HTTPS server — reject unknown hosts
    server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        server_name _;

        ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

        return 444;
    }

    # Per-bot server blocks (auto-generated)
    include /etc/nginx/conf.d/*.conf;
}
MAIN_NGINX_EOF

BOT_COUNT=$(grep -c 'container_name:' "$COMPOSE_FILE" || echo "0")
echo "✅ Generated docker-compose.yml with ${BOT_COUNT} bot(s)"
echo "✅ Generated nginx.conf + ${BOT_COUNT} nginx config(s) for *.${DOMAIN}"
echo "✅ Generated API config for api.${DOMAIN}"
